# Generated by Django 4.2.3 on 2024-03-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created', 'author']},
        ),
    ]
