# Generated by Django 4.2.3 on 2024-04-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_task_created_3b423c_idx',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1L', 'Low'), ('2M', 'Medium'), ('3H', 'High')], default='1L', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1W', 'Waiting'), ('2S', 'Started'), ('3C', 'Completed')], default='1W', max_length=2),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-created', 'author'], name='task_task_created_ce9d77_idx'),
        ),
    ]
