# Generated by Django 4.2.3 on 2024-04-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email_confirmed',
            new_name='email_confrim_status',
        ),
    ]
