# Generated by Django 4.2.3 on 2024-04-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_rename_email_confirmed_userprofile_email_confrim_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email_confrim_status',
            new_name='email_confirm_status',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='users_images'),
        ),
    ]
