# Generated by Django 4.2.3 on 2024-04-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_rename_ulr_notification_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='/users_images/user.png', upload_to='users_images'),
        ),
    ]
